"""
Guodian Glyph Mapper: Connect bamboo slip glyphs to chapters and lexicon.

Maps the 1073 Guodian Laozi A glyph images to:
- DDJ chapter text positions
- Lexicon/Glossary entries
- Translation files
"""

import json
import os
import re
from pathlib import Path
from typing import Dict, List, Optional, Tuple, Any
from collections import defaultdict


class GuodianGlyphMapper:
    """
    Map Guodian Laozi A bamboo slip glyphs to characters and chapters.
    """

    def __init__(self):
        self.project_root = Path(__file__).parent.parent
        self.glyph_folder = self.project_root / "data" / "ddj" / "Guodian Strip Glyphs"
        self.output_dir = self.project_root / "data" / "ddj"

        # Slip-to-chapter mapping from archaeological analysis
        # Format: {slip_number: [(chapter, start_pos, end_pos), ...]}
        self.slip_chapters = {
            1: [(19, 1, 30)],
            2: [(46, 1, 31)],  # 知足
            3: [(66, 1, 31)],
            4: [(66, 1, 31)],
            5: [(66, 1, 31)],
            6: [(46, 1, 25), (30, 26, 31)],
            7: [(30, 1, 31)],
            8: [(15, 1, 31)],
            9: [(15, 1, 31)],
            10: [(15, 1, 31)],
            11: [(64, 1, 31)],
            12: [(63, 1, 31)],
            13: [(37, 1, 31)],
            14: [(37, 1, 34)],
            15: [(2, 1, 33)],  # Co-emergence
            16: [(2, 1, 31)],
            17: [(2, 1, 31)],
            18: [(32, 1, 25)],
            19: [(32, 1, 29)],
            20: [(32, 1, 31)],
            21: [(25, 1, 31)],  # Sphere proof
            22: [(25, 1, 31)],  # Contains 潰 (overflow)
            23: [(25, 1, 31), (5, 20, 31)],  # Bellows
            24: [(16, 1, 31)],  # Return to root
            25: [(64, 1, 31)],
            26: [(64, 1, 16)],
            27: [(56, 1, 31)],  # 玄同
            28: [(56, 1, 31)],
            29: [(56, 1, 10), (57, 11, 31)],
            30: [(57, 1, 31)],
            31: [(57, 1, 31)],
            32: [(57, 1, 22)],
            33: [(55, 1, 31)],
            34: [(55, 1, 31)],  # 知和曰常
            35: [(55, 1, 20), (44, 21, 31)],
            36: [(44, 1, 31)],
            37: [(40, 1, 29)],  # THE CORE ENGINE
            38: [(9, 1, 25)],
            39: [(9, 1, 20)],
        }

        # Load verified transcriptions from JSON (auto-generated from CHUBS)
        # All 19 Guodian Laozi A chapters with position-to-character mappings
        self.verified_transcriptions = self._load_verified_transcriptions()

        # Common phonetic loans in Guodian Laozi
        self.phonetic_loans = {
            "返": "反",  # fǎn - return
            "溺": "弱",  # ruò - weak/yielding
            "僮": "動",  # dòng - movement
            "甬": "用",  # yòng - function/use
            "又": "有",  # yǒu - existence
            "亡": "無",  # wú - non-existence
            "勿": "物",  # wù - things
            "恆": "常",  # cháng - constant (Han taboo change)
            "潰": "逝",  # shì - overflow vs depart
        }

        self._glyphs = None
        self._slip_index = None

    def _load_verified_transcriptions(self) -> Dict:
        """
        Load verified transcriptions from JSON file.

        The JSON file is generated by export_verified_transcriptions.py
        from CHUBS reverse-mapping data.
        """
        json_path = self.output_dir / "verified_transcriptions.json"

        if not json_path.exists():
            # Fallback to Chapter 40 only if JSON not generated yet
            return {
                40: {
                    "slips": [37],
                    "guodian_text": "返也者道僮也溺也者道之甬也天下之勿生於又生於亡",
                    "received_text": "反者道之動弱者道之用天下萬物生於有有生於無",
                    "verification_status": "human_verified",
                    "positions": {}
                }
            }

        with open(json_path, encoding='utf-8') as f:
            data = json.load(f)

        # Convert string keys back to integers/tuples
        result = {}
        for chapter_str, chapter_data in data.items():
            chapter = int(chapter_str)

            # Convert position keys
            positions = {}
            for pos_key, value in chapter_data.get("positions", {}).items():
                if "_" in pos_key:
                    # Multi-slip: "37_5" -> (37, 5)
                    parts = pos_key.split("_")
                    key = (int(parts[0]), int(parts[1]))
                else:
                    key = int(pos_key)

                # Value is [guodian_char, received_char]
                guo = value[0]
                rec = value[1]
                positions[key] = (guo, rec)

            result[chapter] = {
                "slips": chapter_data["slips"],
                "guodian_text": chapter_data["guodian_text"],
                "received_text": chapter_data["received_text"],
                "verification_status": chapter_data.get("verification_status", "auto_generated"),
                "positions": positions
            }

        return result

    @property
    def glyphs(self) -> List[Dict]:
        """Lazy-load and parse all glyph files."""
        if self._glyphs is None:
            self._glyphs = self._scan_glyphs()
        return self._glyphs

    @property
    def slip_index(self) -> Dict[int, List[Dict]]:
        """Index glyphs by slip number."""
        if self._slip_index is None:
            self._slip_index = defaultdict(list)
            for glyph in self.glyphs:
                self._slip_index[glyph["slip"]].append(glyph)
            # Sort each slip by position
            for slip in self._slip_index:
                self._slip_index[slip].sort(key=lambda x: x["position"])
        return self._slip_index

    def _scan_glyphs(self) -> List[Dict]:
        """Scan glyph folder and parse filenames."""
        glyphs = []

        if not self.glyph_folder.exists():
            print(f"Warning: Glyph folder not found: {self.glyph_folder}")
            return glyphs

        # Pattern: 郭店簡_01A-老子甲_{slip}_{01A-{slip}-{position}}.png
        pattern = re.compile(r'郭店簡_01A-老子甲_(\d+)_01A-\d+-(\d+)\.png')

        for f in self.glyph_folder.glob("*.png"):
            match = pattern.match(f.name)
            if match:
                slip = int(match.group(1))
                position = int(match.group(2))
                glyphs.append({
                    "filename": f.name,
                    "path": str(f),
                    "slip": slip,
                    "position": position,
                    "bundle": "A",  # All are Laozi A
                })

        return glyphs

    def get_slip_glyphs(self, slip_num: int) -> List[Dict]:
        """Get all glyphs for a specific slip, sorted by position."""
        return self.slip_index.get(slip_num, [])

    def get_glyph(self, slip: int, position: int) -> Optional[Dict]:
        """Get a specific glyph by slip and position."""
        for glyph in self.slip_index.get(slip, []):
            if glyph["position"] == position:
                return glyph
        return None

    def get_chapter_glyphs(self, chapter_num: int) -> List[Dict]:
        """Get all glyphs for a chapter based on slip mappings."""
        glyphs = []

        for slip, chapters in self.slip_chapters.items():
            for ch, start_pos, end_pos in chapters:
                if ch == chapter_num:
                    slip_glyphs = self.get_slip_glyphs(slip)
                    for glyph in slip_glyphs:
                        if start_pos <= glyph["position"] <= end_pos:
                            glyphs.append({
                                **glyph,
                                "chapter": chapter_num,
                            })

        return glyphs

    def generate_chapter_mapping(self, chapter_num: int) -> Dict:
        """
        Generate glyph mapping for a chapter.
        Uses verified transcriptions where available.
        """
        if chapter_num in self.verified_transcriptions:
            return self._generate_verified_mapping(chapter_num)
        else:
            return self._generate_provisional_mapping(chapter_num)

    def _generate_verified_mapping(self, chapter_num: int) -> Dict:
        """Generate mapping from verified transcription data."""
        data = self.verified_transcriptions[chapter_num]
        mapping = {
            "chapter": chapter_num,
            "verified": True,
            "slips": data["slips"],
            "guodian_text": data["guodian_text"],
            "received_text": data["received_text"],
            "glyphs": []
        }

        for slip in data["slips"]:
            for pos, (guo_char, rec_char) in data["positions"].items():
                glyph = self.get_glyph(slip, pos)
                if glyph:
                    mapping["glyphs"].append({
                        "slip": slip,
                        "position": pos,
                        "guodian_char": guo_char,
                        "received_char": rec_char,
                        "is_loan": guo_char != rec_char and rec_char is not None,
                        "path": glyph["path"],
                        "filename": glyph["filename"],
                    })

        return mapping

    def _generate_provisional_mapping(self, chapter_num: int) -> Dict:
        """Generate provisional mapping (glyphs without character assignments)."""
        glyphs = self.get_chapter_glyphs(chapter_num)

        return {
            "chapter": chapter_num,
            "verified": False,
            "slips": list(set(g["slip"] for g in glyphs)),
            "guodian_text": None,
            "received_text": None,
            "glyphs": [{
                "slip": g["slip"],
                "position": g["position"],
                "guodian_char": None,  # Needs verification
                "received_char": None,
                "is_loan": None,
                "path": g["path"],
                "filename": g["filename"],
            } for g in glyphs],
            "needs_transcription": True,
        }

    def export_all_mappings(self) -> Dict:
        """Export mappings for all chapters."""
        # Get all chapters from slip mappings
        all_chapters = set()
        for chapters in self.slip_chapters.values():
            for ch, _, _ in chapters:
                all_chapters.add(ch)

        mappings = {}
        for ch in sorted(all_chapters):
            mappings[ch] = self.generate_chapter_mapping(ch)

        return mappings

    def export_slip_inventory(self) -> Dict:
        """Export complete slip-by-slip inventory."""
        inventory = {}

        for slip_num in sorted(self.slip_index.keys()):
            glyphs = self.slip_index[slip_num]
            chapters = self.slip_chapters.get(slip_num, [])

            inventory[slip_num] = {
                "slip": slip_num,
                "bundle": "A",
                "glyph_count": len(glyphs),
                "positions": [g["position"] for g in glyphs],
                "chapters": [{"chapter": ch, "start": s, "end": e} for ch, s, e in chapters],
                "glyphs": [{
                    "position": g["position"],
                    "filename": g["filename"],
                    "path": g["path"],
                } for g in glyphs]
            }

        return inventory

    def generate_glossary_links(self) -> Dict[str, List[Dict]]:
        """
        Generate character → glyph links for the Living Glossary.
        Uses verified transcriptions and phonetic loan mappings.
        """
        char_glyphs = defaultdict(list)

        # Process verified transcriptions
        for chapter, data in self.verified_transcriptions.items():
            for slip in data["slips"]:
                for pos, (guo_char, rec_char) in data["positions"].items():
                    glyph = self.get_glyph(slip, pos)
                    if glyph:
                        # Link to Guodian character
                        if guo_char:
                            char_glyphs[guo_char].append({
                                "chapter": chapter,
                                "slip": slip,
                                "position": pos,
                                "path": glyph["path"],
                                "is_exemplar": True,  # From verified transcription
                            })
                        # Also link to received character if different
                        if rec_char and rec_char != guo_char:
                            char_glyphs[rec_char].append({
                                "chapter": chapter,
                                "slip": slip,
                                "position": pos,
                                "path": glyph["path"],
                                "is_loan_form": True,
                                "loan_char": guo_char,
                            })

        return dict(char_glyphs)

    def save_mappings(self):
        """Save all mapping data to JSON files."""
        self.output_dir.mkdir(parents=True, exist_ok=True)

        # Save chapter mappings
        mappings = self.export_all_mappings()
        with open(self.output_dir / "guodian_chapter_mappings.json", "w", encoding="utf-8") as f:
            json.dump(mappings, f, ensure_ascii=False, indent=2)

        # Save slip inventory
        inventory = self.export_slip_inventory()
        with open(self.output_dir / "guodian_slip_inventory.json", "w", encoding="utf-8") as f:
            json.dump(inventory, f, ensure_ascii=False, indent=2)

        # Save glossary links
        links = self.generate_glossary_links()
        with open(self.output_dir / "guodian_glossary_links.json", "w", encoding="utf-8") as f:
            json.dump(links, f, ensure_ascii=False, indent=2)

        print(f"Saved mappings to {self.output_dir}")
        return {
            "chapter_mappings": len(mappings),
            "slips": len(inventory),
            "glossary_chars": len(links),
        }

    def get_stats(self) -> Dict:
        """Get statistics about the glyph collection."""
        glyphs = self.glyphs
        slips = self.slip_index

        verified_chapters = list(self.verified_transcriptions.keys())

        return {
            "total_glyphs": len(glyphs),
            "total_slips": len(slips),
            "slips_range": f"1-{max(slips.keys())}" if slips else "none",
            "verified_chapters": verified_chapters,
            "unverified_chapters": [ch for ch in set(
                ch for chapters in self.slip_chapters.values()
                for ch, _, _ in chapters
            ) if ch not in verified_chapters],
            "phonetic_loans": list(self.phonetic_loans.keys()),
        }


def main():
    """Demo the mapper."""
    mapper = GuodianGlyphMapper()

    print("=== Guodian Glyph Mapper ===\n")

    # Get stats
    stats = mapper.get_stats()
    print(f"Total glyphs: {stats['total_glyphs']}")
    print(f"Total slips: {stats['total_slips']} ({stats['slips_range']})")
    print(f"Verified chapters: {stats['verified_chapters']}")
    print(f"Unverified chapters: {len(stats['unverified_chapters'])} chapters")
    print(f"Phonetic loans tracked: {len(stats['phonetic_loans'])}")

    # Show Chapter 40 mapping (verified)
    print("\n=== Chapter 40 (Verified) ===")
    ch40 = mapper.generate_chapter_mapping(40)
    print(f"Guodian text: {ch40['guodian_text']}")
    print(f"Received text: {ch40['received_text']}")
    print(f"Glyph count: {len(ch40['glyphs'])}")
    print("\nGlyph positions:")
    for g in ch40["glyphs"][:5]:
        loan_marker = " [LOAN]" if g["is_loan"] else ""
        print(f"  {g['slip']}-{g['position']:02d}: {g['guodian_char']} → {g['received_char']}{loan_marker}")
    print("  ...")

    # Show slip 37 inventory
    print("\n=== Slip 37 (Chapter 40) ===")
    slip37 = mapper.get_slip_glyphs(37)
    print(f"Glyphs: {len(slip37)}")
    print(f"Positions: {[g['position'] for g in slip37]}")

    # Save mappings
    print("\n=== Saving Mappings ===")
    result = mapper.save_mappings()
    print(f"Saved: {result['chapter_mappings']} chapter mappings")
    print(f"Saved: {result['slips']} slip inventories")
    print(f"Saved: {result['glossary_chars']} glossary character links")


if __name__ == "__main__":
    main()
