#!/usr/bin/env python3
"""
NotebookLM Document Organizer
Categorizes processed docs and creates set directories.

Usage:
    python scripts/nlm_organize.py
    python scripts/nlm_organize.py --dry-run
"""

import shutil
import argparse
from pathlib import Path
from datetime import date

# ============= CONFIGURATION =============
REPO = Path("/Users/willgoldstein/claudecode/ourinfinitereality_sandbox")
PROCESSED_DIR = REPO / "notebooklm_processed"
SETS_DIR = REPO / "sets"

# ============= SET DEFINITIONS =============

SET_DEFINITIONS = {
    'nlm-core': {
        'set_name': 'NotebookLM Core Theory',
        'description': 'Foundational RSM theory documents generated by NotebookLM including white papers and formal treatments',
        'files': [
            'white_paper_rsm.md',
            'universe_as_verb.md',
            'rsm_falsifiable_framework.md',
        ],
        'keywords': [
            'RSM',
            'white paper',
            'formal treatment',
            'V₀ prohibition',
            'persistence',
        ],
    },
    'nlm-reference': {
        'set_name': 'NotebookLM Reference Materials',
        'description': 'Glossaries, guides, and reference documents for RSM terminology and voice',
        'files': [
            'foundational_glossary.md',
            'voice_guide.md',
        ],
        'keywords': [
            'glossary',
            'reference',
            'terminology',
            'voice guide',
        ],
    },
    'nlm-dialogues': {
        'set_name': 'NotebookLM Dialogues',
        'description': 'Socratic dialogues exploring RSM concepts through conversation between characters',
        'files': [
            'dialogue_physicist_sage.md',
            'seven_dialogues.md',
            'dialogue_sailor_to_sisyphus.md',
        ],
        'keywords': [
            'dialogue',
            'Socratic',
            'physicist',
            'sage',
            'Laozi',
            'Einstein',
        ],
    },
    'nlm-parables': {
        'set_name': 'NotebookLM Parables',
        'description': 'Teaching stories and allegorical narratives illustrating RSM principles',
        'files': [
            'parable_kai_unmeasurable_field.md',
            'the_sailors_paradox.md',
            'sailor_and_waves.md',
            'sisyphus_breath.md',
            'true_punishment.md',
        ],
        'keywords': [
            'parable',
            'teaching story',
            'Kai',
            'sailor',
            'Sisyphus',
            'allegory',
        ],
    },
    'nlm-essays': {
        'set_name': 'NotebookLM Essays',
        'description': 'Technical essays on RSM applications, interpretations, and connections',
        'files': [
            'the_loom_and_the_forge.md',
            'wu_wei_gardeners_principle.md',
            'introduction_to_the_laozi.md',
        ],
        'keywords': [
            'essay',
            'wu wei',
            'Laozi',
            'application',
        ],
    },
}


def generate_set_yaml(set_id: str, set_def: dict) -> str:
    """Generate _set.yaml content for a set."""
    files = set_def['files']
    primary = f"01_{files[0]}" if files else None

    lines = [
        f'set_id: "{set_id}"',
        f'set_name: "{set_def["set_name"]}"',
        'version: "0.993"',
        f'description: "{set_def["description"]}"',
        f'file_count: {len(files)}',
        f'primary_file: "{primary}"' if primary else 'primary_file: null',
        f'entry_point: "{primary}"' if primary else 'entry_point: null',
        'source: "notebooklm"',
        f'generation_date: "2026-01-05"',
        'dependencies:',
        '  - "rsm-core"',
        'keywords:',
    ]

    for kw in set_def['keywords']:
        lines.append(f'  - "{kw}"')

    lines.extend([
        'notebooklm_load_with:',
        '  - "rsm-core"',
    ])

    # Add nlm-core as dependency for non-core sets
    if set_id != 'nlm-core':
        lines.append('  - "nlm-core"')

    lines.extend([
        f'last_updated: "{date.today()}"',
        'authors:',
        '  - "NotebookLM"',
        '  - "Will Goldstein"',
        '  - "Claude"',
    ])

    return '\n'.join(lines) + '\n'


def organize_documents(dry_run: bool = False):
    """Organize processed documents into sets."""
    if not PROCESSED_DIR.exists():
        print(f"ERROR: Processed directory not found: {PROCESSED_DIR}")
        print("Run nlm_process.py first.")
        return

    print("=== NotebookLM Document Organizer ===")
    print(f"Source:  {PROCESSED_DIR}")
    print(f"Target:  {SETS_DIR}")
    print(f"Mode:    {'DRY RUN' if dry_run else 'ORGANIZING'}")
    print()

    total_files = 0
    missing_files = []

    for set_id, set_def in SET_DEFINITIONS.items():
        set_dir = SETS_DIR / set_id
        print(f"--- {set_id} ({len(set_def['files'])} files) ---")

        if not dry_run:
            set_dir.mkdir(exist_ok=True)

        # Copy files with numeric prefixes
        for idx, filename in enumerate(set_def['files'], 1):
            src = PROCESSED_DIR / filename
            prefix = f"{idx:02d}_"
            dst_name = f"{prefix}{filename}"
            dst = set_dir / dst_name

            if src.exists():
                if not dry_run:
                    shutil.copy2(src, dst)
                print(f"  ✓ {filename} -> {dst_name}")
                total_files += 1
            else:
                print(f"  ✗ {filename} (NOT FOUND)")
                missing_files.append(filename)

        # Generate _set.yaml
        set_yaml = generate_set_yaml(set_id, set_def)
        yaml_path = set_dir / '_set.yaml'

        if not dry_run:
            yaml_path.write_text(set_yaml, encoding='utf-8')
        print(f"  ✓ _set.yaml")
        print()

    # Summary
    print("=== Summary ===")
    print(f"Sets created: {len(SET_DEFINITIONS)}")
    print(f"Files copied: {total_files}")

    if missing_files:
        print(f"\nMissing files ({len(missing_files)}):")
        for f in missing_files:
            print(f"  - {f}")

    if not dry_run:
        print(f"\nSets directory: {SETS_DIR}")
        print("\nNext steps:")
        print("  1. Run: ./scripts/generate_all_sets.sh")
        print("  2. Verify: ls docset/set_nlm-*.md")


def main():
    parser = argparse.ArgumentParser(description='Organize NotebookLM documents into sets')
    parser.add_argument('--dry-run', action='store_true', help='Preview without writing')
    args = parser.parse_args()

    organize_documents(dry_run=args.dry_run)


if __name__ == "__main__":
    main()
